/* STUDENT DETAILS*/
SELECT S.STUDENT_ID, CONCAT(S.FIRST_NAME,' ', S.LAST_NAME) AS "Name", S.HOME_PHONE_NUMBER AS Home, S.CELL_PHONE_NUMBER AS Cell 
FROM STUDENT S WHERE S.STUDENT_ID = 991662275; 

/*STUDENT CURRENT COURSES*/
SELECT C.COURSE_CODE AS "COURSE CODE", C.COURSE_NAME AS "COURSE NAME" 
FROM STUDENT S JOIN STUDENT_INSTRUCTOR_COURSE SIC ON S.STUDENT_ID = SIC.STUDENT_ID 
JOIN INSTRUCTOR_COURSE IC ON SIC.INSTRUCTOR_COURSE_ID = IC.INSTRUCTOR_COURSE_ID 
JOIN COURSE C ON IC.COURSE_CODE = C.COURSE_CODE WHERE S.STUDENT_ID = 991662275 AND IC.TERM = "FALL2022";

/*STUDENT ACADEMIC HISTORY*/
/*INSTRUCTOR DETAILS CAN ALSO BE DISPLAYED*/
SELECT C.COURSE_CODE AS "COURSE CODE", C.COURSE_NAME AS "COURSE NAME" , IC.TERM ,SIC.GRADES
FROM STUDENT S JOIN STUDENT_INSTRUCTOR_COURSE SIC ON S.STUDENT_ID = SIC.STUDENT_ID 
JOIN INSTRUCTOR_COURSE IC ON SIC.INSTRUCTOR_COURSE_ID = IC.INSTRUCTOR_COURSE_ID 
JOIN COURSE C ON IC.COURSE_CODE = C.COURSE_CODE WHERE S.STUDENT_ID = 991662275 AND IC.TERM != "FALL2022";

/* TO SEE ALL THE AVAILABLE PROGRAMS */
SELECT P.PROGRAM_CODE AS "PROGRAM CODE", P.PROGRAM_NAME AS "PROGRAM", count(STUDENT_ID) AS "ENROLLMENT"
FROM PROGRAM P JOIN STUDENT S ON S.PROGRAM_CODE = P.PROGRAM_CODE GROUP BY P.PROGRAM_CODE;

/* TO SEE ALL THE STUDENT DETAILS */
SELECT S.STUDENT_ID, S.LAST_NAME AS "LAST NAME", S.FIRST_NAME AS "FIRST NAME", S.HOME_PHONE_NUMBER AS "HOME PHONE NUMBER", S.CELL_PHONE_NUMBER AS "CELL PHONE NUMBER",
S.EMAIL, S.PROGRAM_CODE, P.PROGRAM_NAME AS "PROGRAM" FROM STUDENT S JOIN PROGRAM P ON S.PROGRAM_CODE =  P.PROGRAM_CODE;


/* To see all the instructers */
SELECT I.INSTRUCTOR_ID, I.LAST_NAME AS "LAST NAME", I.FIRST_NAME AS "FIRST NAME", I.PHONE_NO AS "PHONE NUMBER" ,I.EMAIL, I.DEPARTMENT_CODE AS "DEPARTMENT CODE", D.DEPARTMENT_NAME AS "DEPARTMENT NAME"
 FROM INSTRUCTOR I JOIN DEPARTMENT D ON I.DEPARTMENT_CODE = D. DEPARTMENT_CODE;
 
 /* COURSE OFFERING */
use crs;
SELECT IC.INSTRUCTOR_COURSE_ID AS "Offering Code", IC.COURSE_CODE AS "Course Code", C.COURSE_NAME AS "Course Name",
IC.TERM AS "Semester", CONCAT(I.FIRST_NAME,' ',I.LAST_NAME)  AS Instructor, COUNT(s.student_id) AS "Enrollment"
FROM
 INSTRUCTOR_COURSE IC JOIN STUDENT_INSTRUCTOR_COURSE SIC ON IC.INSTRUCTOR_COURSE_ID = SIC.INSTRUCTOR_COURSE_ID JOIN 
 INSTRUCTOR I ON IC.INSTRUCTOR_ID = I.INSTRUCTOR_ID JOIN 
 COURSE C ON IC.COURSE_CODE = C.COURSE_CODE JOIN 
 STUDENT S ON SIC.STUDENT_ID = S.STUDENT_ID
 GROUP BY I.INSTRUCTOR_ID order by IC.INSTRUCTOR_COURSE_ID;
 
	
